#!/usr/bin/env python3
"""Seal the sequence-derived interior-gauge One-extension correction.

The published 76-state material path is preserved through residue 75.  When a
terminal One advance is added, the old C-terminal psi ceases to be a gauge.
Its newly observable value, and the new terminal phi, are generated by the
already frozen sequence-only transfer command.  Targets and scores are absent.
"""
from __future__ import annotations

import argparse
from hashlib import sha256
import json
import os
from pathlib import Path
import shutil
import tempfile
import time

from tools.blind_24_lattice_selector_v3 import angles_for_state
from tools.protein_backbone_geometry_v1 import build_backbone_coordinates, write_pdb
from tools.protein_transfer_material_command_v2 import material_state_path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "verify/ubiquitin_24_lattice_manifest.json"
COMMAND = ROOT / "verify/protein_transfer_material_command_v2.json"
SCHEMA = "fold-protein-blind-material-one-extension-panel/v2"


def file_sha256(path: Path) -> str:
    return sha256(path.read_bytes()).hexdigest()


def json_bytes(value) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode()


def extension_path(sequence: str, manifest: dict, command: dict) -> dict:
    template = manifest["sequence"]
    if len(sequence) != len(template) + 1 or not sequence.startswith(template):
        raise RuntimeError("sequence is not the exact theorem-forced One extension")
    parent = [int(value) for value in manifest["states"]]
    generated = material_state_path(sequence, command)
    old_terminal = len(template) - 1
    old_phi = parent[old_terminal] // 24
    interior_psi = generated["psi_axis"][old_terminal]
    new_terminal_phi = generated["phi_axis"][old_terminal + 1]
    states = parent[:-1] + [old_phi * 24 + interior_psi, new_terminal_phi * 24]
    return {
        "states": states,
        "former_terminal_interior_psi": interior_psi,
        "new_terminal_phi": new_terminal_phi,
        "sequence_command_trace": [
            row for row in generated["command_trace"]
            if row["residue_position_one_based"] >= len(template)
        ],
    }


def run(registration_path: Path, output_dir: Path) -> dict:
    registration_path = registration_path.resolve()
    output_dir = output_dir.resolve()
    if output_dir.exists():
        raise FileExistsError(output_dir)
    raw = registration_path.read_bytes()
    registration = json.loads(raw)
    if (registration.get("schema") != SCHEMA
            or registration.get("blind_prediction") is not True
            or registration.get("target_accesses_before_seal") != 0):
        raise RuntimeError("blind One-extension V2 registration drifted")
    runtime = Path(__file__).resolve()
    bindings = {
        "runtime_sha256": file_sha256(runtime),
        "published_manifest_sha256": file_sha256(MANIFEST),
        "sequence_command_sha256": file_sha256(COMMAND),
    }
    for key, actual in bindings.items():
        if registration.get(key) != actual:
            raise RuntimeError(f"blind One-extension V2 binding drifted: {key}")
    manifest = json.loads(MANIFEST.read_text())
    command = json.loads(COMMAND.read_text())

    stage = Path(tempfile.mkdtemp(
        prefix="fold-protein-blind-one-extension-v2-", dir=output_dir.parent))
    try:
        (stage / "panel_registration.json").write_bytes(raw)
        runs = []
        for protein in registration["proteins"]:
            sequence = protein["sequence"]
            relation = extension_path(sequence, manifest, command)
            states = relation["states"]
            started = time.perf_counter()
            atoms = build_backbone_coordinates(
                sequence,
                [angles_for_state(state)[0] for state in states],
                [angles_for_state(state)[1] for state in states],
            )
            nested = stage / protein["protein_id"]
            nested.mkdir()
            write_pdb(atoms, nested / "prediction.pdb")
            selected = {
                "schema": "fold-protein-blind-material-one-extension-states/v2",
                "status": "completed",
                "result_type": "cumulative blind development benchmark",
                "official_run": False,
                "blind_prediction": True,
                "protein_id": protein["protein_id"],
                "sequence": sequence,
                "sequence_sha256": sha256(sequence.encode()).hexdigest(),
                **relation,
                "weights": 0,
                "fitted_parameters": 0,
                "target_accesses": 0,
                "elapsed_seconds": time.perf_counter() - started,
            }
            selected_raw = json_bytes(selected)
            (nested / "selected_states.json").write_bytes(selected_raw)
            seal = {
                "schema": "fold-protein-blind-material-one-extension-seal/v2",
                "status": "completed",
                "blind_prediction": True,
                "protein_id": protein["protein_id"],
                "sequence_sha256": selected["sequence_sha256"],
                "selected_states_sha256": sha256(selected_raw).hexdigest(),
                "prediction_pdb_sha256": file_sha256(nested / "prediction.pdb"),
                **bindings,
                "weights": 0,
                "fitted_parameters": 0,
                "target_accesses": 0,
            }
            seal_raw = json_bytes(seal)
            (nested / "seal.json").write_bytes(seal_raw)
            runs.append({
                "protein_id": protein["protein_id"],
                "sequence_sha256": seal["sequence_sha256"],
                "selected_states_sha256": seal["selected_states_sha256"],
                "prediction_pdb_sha256": seal["prediction_pdb_sha256"],
                "nested_seal_sha256": sha256(seal_raw).hexdigest(),
            })
        panel = {
            "schema": "fold-protein-blind-material-one-extension-panel-seal/v2",
            "status": "completed",
            "result_type": "cumulative blind development benchmark",
            "official_run": False,
            "blind_prediction": True,
            "panel_id": registration["panel_id"],
            "panel_registration_sha256": sha256(raw).hexdigest(),
            **bindings,
            "prediction_count": len(runs),
            "target_accesses_before_seal": 0,
            "runs": runs,
        }
        (stage / "panel_seal.json").write_bytes(json_bytes(panel))
        os.replace(stage, output_dir)
        return panel
    except Exception:
        shutil.rmtree(stage, ignore_errors=True)
        raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("registration", type=Path)
    parser.add_argument("output_dir", type=Path)
    args = parser.parse_args()
    print(json.dumps(run(args.registration, args.output_dir), sort_keys=True))
